apiVersion: v1
kind: Pod
metadata:
  name: gcsfuse-test
  namespace: default
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  activeDeadlineSeconds: 50000
  nodeSelector:
    cloud.google.com/gke-nodepool: n2-96-node-pool
  hostNetwork: true
  containers:
  - image: ubuntu:22.04
    name: ubuntu
    securityContext:
      privileged: true
    command: ["sleep" ,"infinity"]
    resources:
      requests:
        memory: "0"
        cpu: "0"
      limits:
        memory: "0"
        cpu: "0"
    volumeMounts:
    - name: data-vol
      mountPath: /data
    - name: dshm
      mountPath: /shm
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  - name: gke-gcsfuse-cache
    emptyDir:
      medium: Memory
  - name: data-vol
    csi:
      driver: gcsfuse.csi.storage.gke.io
      volumeAttributes:
        bucketName: anushkadhn-llama2
        metadataCacheTTLSeconds: "-1"
        metadataTypeCacheCapacity: "-1"
        metadataStatCacheCapacity: "-1"
        fileCacheCapacity: "-1"
        fileCacheForRangeRead: "true"
        gcsfuseLoggingSeverity: "info"
        disableMetrics: "true"
        mountOptions: "implicit-dirs,gcs-connection:client-protocol:http1,file-cache:enable-parallel-downloads:true"

