apiVersion: v1
kind: Pod
metadata:
  name: gcsfuse-test
  namespace: default
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  activeDeadlineSeconds: 50000
  nodeSelector:
    cloud.google.com/gke-nodepool: <nodepool>
  hostNetwork: true
  containers:
  - image: ubuntu:22.04
    name: ubuntu
    securityContext:
      privileged: true
    command: ["sleep" ,"infinity"]
    resources:
      requests:
        memory: "0"
        cpu: "0"
      limits:
        memory: "0"
        cpu: "0"
    volumeMounts:
    - name: data-vol
      mountPath: /data
  volumes:
  - name: data-vol
    csi:
      driver: gcsfuse.csi.storage.gke.io
      volumeAttributes:
        bucketName: <bucket>
        fileCacheCapacity: "0"
        mountOptions: "implicit-dirs,file-cache:max-size-mb:0,gcs-connection:client-protocol:http1"
        disableMetrics: "true"
