apiVersion: v1
kind: Pod
metadata:
  name: gcsfuse-test
  namespace: default
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  activeDeadlineSeconds: 50000
  nodeSelector:
    cloud.google.com/gke-tpu-topology: 2x2
    cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
    cloud.google.com/gke-nodepool: <node-pool>
  hostNetwork: true
  containers:
  - image: ubuntu:22.04
    name: ubuntu
    securityContext:
      privileged: true
    command: ["sleep" ,"infinity"]
    resources:
      requests:
        memory: "0"
        cpu: "0"
      limits:
        memory: "0"
        cpu: "0"
